# Generated by Django 4.1.4 on 2022-12-30 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autofill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website", models.CharField(default="", max_length=256)),
                ("autofill", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="Qzq6eTNLIuN-U3DEy3Byb",
                        max_length=21,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MinLengthValidator(21)],
                    ),
                ),
                ("website", models.CharField(default="", max_length=256)),
                ("password", models.CharField(default="", max_length=256)),
                ("login", models.CharField(default="", max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
