# Generated by Django 4.1.4 on 2022-12-31 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Credentials",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                ("website", models.URLField(max_length=256)),
                ("password", models.CharField(max_length=256)),
                ("login", models.CharField(max_length=256)),
                ("created_at", models.BigIntegerField()),
                ("autofill", models.BooleanField(default=True)),
            ],
        ),
    ]
