# Generated by Django 4.1.4 on 2022-12-31 08:48

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentials",
            name="password",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=256)),
        ),
    ]
