# Generated by Django 4.1.4 on 2022-12-31 09:59

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_credentials_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentials",
            name="website",
            field=models.CharField(
                max_length=256, validators=[base.models.validate_url]
            ),
        ),
    ]
