# Generated by Django 4.1.4 on 2023-01-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_credentials_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentials",
            name="updated_at",
            field=models.BigIntegerField(default=0),
        ),
    ]
